# Generated by Django 4.1.1 on 2022-10-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DOSEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIM', models.CharField(max_length=50)),
                ('NAMA', models.CharField(max_length=40)),
                ('TTL', models.CharField(max_length=40)),
                ('PHOTO', models.CharField(max_length=40)),
                ('EMAIL', models.CharField(max_length=40)),
                ('FAKULTAS', models.CharField(max_length=40)),
                ('PRODI', models.CharField(max_length=40)),
                ('ALAMAT', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MAHASISWA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIM', models.CharField(max_length=50)),
                ('NAMA', models.CharField(max_length=40)),
                ('TTL', models.CharField(max_length=40)),
                ('PHOTO', models.CharField(max_length=40)),
                ('EMAIL', models.CharField(max_length=40)),
                ('FAKULTAS', models.CharField(max_length=40)),
                ('PRODI', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='STAFF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=50)),
                ('NAMA', models.CharField(max_length=40)),
                ('TTL', models.CharField(max_length=40)),
                ('PHOTO', models.CharField(max_length=40)),
                ('EMAIL', models.CharField(max_length=40)),
                ('UNIT', models.CharField(max_length=40)),
                ('ALAMAT', models.CharField(max_length=40)),
            ],
        ),
    ]
